app:main.o add.o mul.o div.o cut.o
	gcc main.o add.o mul.o div.o cut.o -o app
main.o:main.c
	gcc -c main.c -o main.o
add.o:add.c
	gcc -c add.c -o add.o
mul.o:mul.c
	gcc -c mul.c -o mul.o
div.o:div.c
	gcc -c div.c -o div.o
cut.o:cut.c
	gcc -c cut.c -o cut.o
